Bump priority of interactive design type
guardian/content-api-scala-client pull request #331
Opened 2021-05-26 15:48 UTC by nicl

Small tweak to bump priority of interactive design type as there are cases where this is currently wrong. E.g.

https://www.theguardian.com/australia-news/ng-interactive/2021/may/11/budget-speech-2021-australia-treasurer-josh-frydenberg-full-address-annotated-what-we-can-read-between-the-lines

Note, as format is new, I don't think there is a direct parallel to Frontend behaviour. I don't think Interactives can currently be displayed as other formats (in Frontend) but if you know better please correct me!

2021-05-26 15:58 UTC, buck06191 requested changes
I'm not sure in terms of Editorial/business logic where Interactives should sit compared to those it has now been bumped past. It's always worth considering whether anything it's being bumped past should ever take higher priority (that's a difficult decision to make).

Assuming that's fine, we need to add unit tests whenever we make a PR like this so that any future changes are caught by it. In this case I'd add a test for the specific broken example given.

2021-05-26 15:58 UTC, buck06191 commented on client/src/main/scala/com.gu.contentapi.client/utils/CapiModelEnrichment.scala
> +        isInteractive -> InteractiveDesign,
Whenever we make the decision to bump the specificity of a `Format` aspect e.g. `Design`, we need to add a unit test to make sure that any future changes don't clash.

2021-05-26 16:00 UTC, buck06191 commented
The example article given here is already `InteractiveDesign`
![image](https://user-images.githubusercontent.com/9122944/119693053-d6288c80-be43-11eb-8e02-2bf48b205059.png)

2021-05-26 16:07 UTC, nicl commented
@buck06191 thanks have updated the example to a correct one.

2022-03-21 15:55 UTC, mxdvl commented
Superceded by #331

2022-03-21 15:55 UTC, closed without merging